'use client';

import { useEffect, useState } from 'react';
import { apiFetch, getAuthToken, API_BASE } from '@/lib/api';

type Client = { id: string; name: string; slug: string; };
type LeadLite = { id: string; displayName: string | null; phone: string | null; };
type QuotationListItem = {
  id: string; status: string; createdAt: string; sentAt?: string | null;
  lead: LeadLite | null; itemCount: number; grandTotal: number; hasPdf: boolean;
};

export default function QuotationsDashboardPage() {
  const [client, setClient] = useState<Client | null>(null);
  const [quotations, setQuotations] = useState<QuotationListItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterLead, setFilterLead] = useState<string>('');

  async function loadDefaultClient() {
    const all = await apiFetch<Client[]>('/api/clients');
    if (!all.length) {
      return await apiFetch<Client>('/api/clients', {
        method: 'POST',
        body: JSON.stringify({ name: 'My First Workspace', slug: `workspace-${Date.now()}` })
      });
    }
    return all[0]!;
  }

  async function loadQuotations() {
    try {
      setLoading(true);
      setError(null);
      const cli = client ?? (await loadDefaultClient());
      setClient(cli);
      const params = new URLSearchParams();
      if (filterLead.trim()) params.set('leadId', filterLead.trim());
      const qs = params.toString() ? `?${params.toString()}` : '';
      const json = await apiFetch<QuotationListItem[]>(`/api/clients/${cli.id}/quotations${qs}`);
      setQuotations(json);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load quotations');
    } finally {
      setLoading(false);
    }
  }

  async function openPdf(q: QuotationListItem) {
    if (!client) return;
    try {
      const token = getAuthToken();
      const res = await fetch(`${API_BASE}/api/clients/${client.id}/quotations/${q.id}/pdf`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {}
      });
      if (!res.ok) throw new Error(await res.text() || 'Failed to fetch PDF');
      const blob = await res.blob();
      window.open(window.URL.createObjectURL(blob), '_blank');
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to open PDF');
    }
  }

  useEffect(() => { void loadQuotations(); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <main className="page-shell">
      <div className="container">
        <section className="hero-card">
          <p className="eyebrow">Quotations</p>
          <h1 className="hero-title">View and download quotations</h1>
          <p className="muted">
            Inspect quotations generated by the WhatsApp assistant, see totals per lead, and open the PDF
            that was sent to the customer.
          </p>
          <div className="cta-row" style={{ marginTop: 20, gap: 12 }}>
            <button className="button button-secondary" disabled={loading} onClick={loadQuotations}>
              {loading ? 'Loading…' : 'Reload Quotations'}
            </button>
          </div>
        </section>

        <section className="panel" style={{ marginTop: 24 }}>
          <p className="eyebrow">Current Client</p>
          {client ? (
            <p className="muted" style={{ marginTop: 8 }}>
              <strong>{client.name}</strong> · slug: <code>{client.slug}</code>
            </p>
          ) : (
            <p className="muted">No client loaded yet.</p>
          )}
        </section>

        <section className="panel" style={{ marginTop: 16 }}>
          <div className="panel-header" style={{ display: 'flex', justifyContent: 'space-between' }}>
            <p className="eyebrow">Quotations</p>
            <div style={{ display: 'flex', gap: 8 }}>
              <input
                type="text"
                placeholder="Filter by lead ID (optional)"
                value={filterLead}
                onChange={(e) => setFilterLead(e.target.value)}
                style={{ minWidth: 220 }}
              />
              <button className="button button-secondary" disabled={loading} onClick={loadQuotations}>
                Apply Filter
              </button>
            </div>
          </div>

          {error && (
            <p className="muted" style={{ marginTop: 8, color: '#ff8888' }}>
              {error}
            </p>
          )}

          {quotations.length === 0 ? (
            <p className="muted" style={{ marginTop: 8 }}>
              No quotations yet. They will appear here when the WhatsApp assistant generates them.
            </p>
          ) : (
            <div style={{ marginTop: 12, overflowX: 'auto' }}>
              <table className="table">
                <thead>
                  <tr>
                    <th>Created</th>
                    <th>Lead</th>
                    <th>Phone</th>
                    <th>Status</th>
                    <th>Items</th>
                    <th>Total (₹)</th>
                    <th>PDF</th>
                  </tr>
                </thead>
                <tbody>
                  {quotations.map((q) => {
                    const created = new Date(q.createdAt).toLocaleString();
                    const leadName = q.lead?.displayName || q.lead?.id || 'Unknown';
                    const phone = q.lead?.phone || '—';
                    const totalFormatted = q.grandTotal.toFixed(2);
                    return (
                      <tr key={q.id}>
                        <td>{created}</td>
                        <td>{leadName}</td>
                        <td>{phone}</td>
                        <td>
                          <span className="pill pill-muted">{q.status}</span>
                        </td>
                        <td>{q.itemCount}</td>
                        <td>{totalFormatted}</td>
                        <td>
                          <button
                            type="button"
                            className="button button-secondary"
                            onClick={() => void openPdf(q)}
                            disabled={loading}
                          >
                            Open PDF
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </div>
    </main>
  );
}

