import Link from 'next/link';

const dashboardCards = [
  {
    title: 'WhatsApp Instances',
    body: 'Create one Evolution instance per client, display QR codes, and monitor live connection state.',
    href: '/dashboard/whatsapp',
    cta: 'Go to WhatsApp setup'
  },
  {
    title: 'Knowledge Sources',
    body: 'Upload PDFs, DOCX, pricing sheets, and website content for chunking, embedding, and retrieval.',
    href: '/dashboard/knowledge',
    cta: 'Manage knowledge'
  },
  {
    title: 'Leads and Meetings',
    body: 'Store captured lead fields, qualification state, quotations, and scheduled meetings in one place.',
    href: '/dashboard/leads',
    cta: 'View leads'
  },
  {
    title: 'Pricing and Quotations',
    body: 'Upload pricing sheets, inspect parsed items, and run sample quotations for your products.',
    href: '/dashboard/pricing',
    cta: 'Manage pricing'
  },
  {
    title: 'Quotations',
    body: 'Review quotations generated by the WhatsApp assistant and open the PDF sent to customers.',
    href: '/dashboard/quotations',
    cta: 'View quotations'
  },
  {
    title: 'Conversations',
    body: 'Inspect WhatsApp conversations and message history captured from Evolution for this client.',
    href: '/dashboard/conversations',
    cta: 'View conversations'
  }
];

export default function DashboardPage() {
  return (
    <main className="page-shell">
      <div className="container">
        <section className="hero-card">
          <p className="eyebrow">Dashboard Shell</p>
          <h1 className="hero-title">Client operations overview</h1>
          <p className="muted">
            This is the starting point for the client-facing UI. Each section below maps directly to a
            backend module and database model in the new platform scaffold.
          </p>
        </section>

        <section className="hero-grid" style={{ marginTop: 24 }}>
          {dashboardCards.map((card) => (
            <article className="panel" key={card.title}>
              <p className="eyebrow">{card.title}</p>
              <p className="muted" style={{ marginTop: 12 }}>
                {card.body}
              </p>
              {card.href && (
                <div className="cta-row" style={{ marginTop: 16 }}>
                  <Link href={card.href} className="button button-secondary">
                    {card.cta || 'Open'}
                  </Link>
                </div>
              )}
            </article>
          ))}
        </section>
      </div>
    </main>
  );
}
